### PR TITLE
implement fs.link_rfiles

### PR DESCRIPTION
**Pull request by varemenos**
this is trying to fix issue #80, honestly I'm not accustomed with the codebase or shell scripting in general so I simply hope it works. Also, I skipped writing a test for it in fs.bats

### CODE REVIEW

**Comment by groggemans** [comment]
Hi @varemenos 

Sorry for my late reply, and thank you for the PR! 

Can you provide some examples for when this would be handy? If you only have one package that needs this, it might be better adding the function to your ellipsis.sh file (or ellipsisrc file, docs coming soon).

We're probably organizing our config files in a different way, so I have no problems adding the function if it helps with your workflow.

Gertjan

**Comment by varemenos** [comment]
Hi Gertjan, you are doing this in your free time so you shouldn't apologize about it, instead it should be me thanking you for taking the time to deal with my nonsense 😃

Anyway, I have setup a few packages for my dot-files and some of them contain files that are not to be prepended with a `.` in their filenames. The current implementation of link_files will go ahead and add a dot anyway, placing the files in a different location than you'd expect them to be. I'd prefer to avoid linking files one by one in the ellipsis.sh config file. It will take too much time to maintain, which (IMHO) shouldn't be the case for maintaining your dotfiles.

_please let me know if this makes sense, my brain is pretty much fried atm and I'm not sure if I managed to convey my issue properly_

**Comment by groggemans** [comment]
The function would link them all in the `ELLIPSIS_HOME` folder (9/10 `$HOME`) wouldn't it make more sense to have such a function that can link in any given directory? (it would make more sense to me :) )

You could always do something like this to mimic that behaviour with the current proposed implementation;
``` bash
ELLIPSIS_HOME=/my/custom/dir fs.link_rfiles /dir1
```

But it would be cleaner if we made something like this;

```bash
# using custom target
fs.link_rfiles /dir1 /target/dir

# using default target
fs.link_rfiles /dir1
```

With the target dir defaulting to `ELLIPSIS_HOME`. 

What do you think about that?

**Comment by varemenos** [comment]
I think, you either misunderstood what is my issue with link_files.

My `pkg.link` looks like this (pretty much a copy/paste from zeekay) :

pkg.link() {
	fs.link_files common

	case $(os.platform) in
		osx)
			fs.link_files platform/osx
			;;
		linux)
			fs.link_files platform/linux
			;;
	esac
}

Now, this is the structure of my package that I linked in my $HOME dir:

---

```
dot-package-name
├── ellipsis.sh
├── common
│   ├── emmet
│   │   ├── preferences.json
│   │   └── syntaxProfiles.json
│   └── hyper.js
├── platform
│   ├── linux
│   │   ├── gnome_shell_extensions_conf.txt
│   │   └── gnome_shell_extensions_id.txt
```

What I will most probably get with link_files:
```
$HOME
├── .emmet
│   ├── preferences.json
│   └── syntaxProfiles.json
├── .hyper.js
├── .gnome_shell_extensions_conf.txt <----  (this will have an unnecessary dot prepended to it)
└── .gnome_shell_extensions_id.txt <---- (this will have an unnecessary dot prepended to it too)
```

---

What I want to achieve with link_rfiles is use this:

```
dot-package-name
├── ellipsis.sh
├── common
│   ├── .emmet
│   │   ├── preferences.json
│   │   └── syntaxProfiles.json
│   └── .hyper.js
├── platform
│   ├── linux
│   │   ├── gnome_shell_extensions_conf.txt
│   │   └── gnome_shell_extensions_id.txt
```

to get this:

```
$HOME
├── .emmet
│   ├── preferences.json
│   └── syntaxProfiles.json
├── .hyper.js
├── gnome_shell_extensions_conf.txt
└── gnome_shell_extensions_id.txt
```

Hope this makes more sense now, and sorry for the long post

**Comment by groggemans** [comment]
NP, makes sense! :+1: 

In my setup, I try to keep the homedir as clean as possible, so most of my config files are under `~/.config/app` (XDG spec), for example `~/.config/vim`. (but some still need a link in `$HOME`) And all my apps have their own packages to improve flexibility and shareability (at higher maintenance cost). 

If we're adding a function to link a bunch of files/dirs, it should be usable in most scenario's, for you it means a lot of files should be linked under `ELLIPSIS_HOME`/`$HOME`, for me a lot of files under `~/.config`, for other people ... ?

Now you probably understand why it didn't make sense to me at first, and why I would add an optional parameter to specify a custom dir.

If you'd like to give it a shot? Otherwise I'll make an implementation myself, but it might take some time.

**Comment by varemenos** [comment]
Ohh, I see... Ya I see no problem there.

I don't mind adding more optional parameters to the function but I'm fairly certain it will take me a full day to write it. I understand that I have to use `fs.link_file filename` if the second parameter doesn't have a value and `fs.link_file filename $2` if there is one but I have no idea how to write it.

Shell scripting is chaos :)

**Comment by groggemans** [comment]
Bash definitely has some special behavior from time to time!

It will take me a fraction of that time, so spare your day of work, and I'll try to make some time tomorrow :)

**Comment by groggemans** [comment]
@varemenos #82 ok for you?

**Comment by varemenos** [comment]
Yes that looks amazing, great work (love how you cleaned up the docs too)

**Comment by groggemans** [comment]
closed in favor of #82

**Pull request closed without merging**
