### PR TITLE
Added wget command for installing Ellipsis

### PR DESCRIPTION
**Pull request by kevinkjt2000**
I was installing [stack](https://docs.haskellstack.org/en/stable/install_and_upgrade/) earlier today, and realized that the same wget command would probably work for installing Ellipsis.

### CODE REVIEW

**Comment by groggemans** [comment]
Thanks for the PR, something I wanted to add for a long time now.

Just updating the README won't be enough I'm afraid. You must also update the dependency checks and code in the installer shim (scripts/shim.sh). The installer also has some tests that should be updated for completeness.

**Comment by kevinkjt2000** [comment]
Then I shall investigate scripts/shim.sh.  Although I was able to install Ellipsis on a machine that never had Ellipsis before from that wget command and it seemed to function normally.

**Comment by kevinkjt2000** [comment]
After reading that script, I see that it would not have worked if curl had not been also installed.  Alright, more work to do then.

**Comment by groggemans** [comment]
There's a dependency check in scripts/installer.sh too.

Ellipsis installs itself in 2 steps. First you get the shim, this will then get the real install script. If you don't alter the shim, curl is still used for getting the real install script.

The dependency check in the real installer script can in theory just ignore the curl dependency, as this is only needed for getting the installer itself. There is still one function that uses curl, but it's currently not used by Ellipsis itself.

**Comment by kevinkjt2000** [comment]
I cloned the ellipsis repo to a location other than ~/.ellipsis.  Now I am trying to run the bats tests.  I exported BATS_TEST_DIRNAME to be the directory of cloned-ellipsis/test.  Then I tried bats *.bats and saw quite a few failures.  Is there more to setting up tests other than BATS_TEST_DIRNAME?

**Comment by kevinkjt2000** [comment]
I decided to look at the Travis-CI server to see how tests are run there, and I noticed `make test`... I'm facepalming myself.  Tests are all passing in my cloned repo.

**Comment by kevinkjt2000** [comment]
Come to think of it, is wget support even needed?  curl is everywhere.  And it is much more actively maintained https://www.openhub.net/p/_compare?project_0=cURL&project_1=Wget
The author of curl has quite a bit to say too https://daniel.haxx.se/docs/curl-vs-wget.html

**Comment by zeekay** [comment]
I chose curl for that reason. Almost always available.

**Comment by kevinkjt2000** [comment]
With my sudden loss of interest in Wget, I will close this request.  Wget is cool when it comes to downloading trees of files from websites, but cURL is much better suited at downloading individual files and piping them to stdout by default.  I see no reason restructure dependency verification or tests, just to allow cURL to be missing from the system.

**Comment by zeekay** [comment]
Thanks!

**Pull request closed without merging**
