### PR TITLE
Make it possible to customize package prefix

### PR DESCRIPTION
**Pull request by groggemans**
As proposed in #77

Also added a few `pkg` test and updated a few functions to use `<<<` instead of an echo + pipe.

### CODE REVIEW

**Comment by zeekay** [comment]
Would be good to test w/o any prefix. Would it make sense to default to no prefix and fall back to dot- if repo missing?

**Comment by groggemans** [comment]
It makes sense, but I'm not sure it's worth the added complexity. Installs will also be slower because of the extra git or curl requests. Users might also get confused what will be used when.

Another approach would be to always do installs based on the full name (no prefixes) and have an alias setting in `ellipsis.sh` thats used as name for the installation folder and CLI interaction.

The implementation in this PR just makes the current behavior more flexible. So it might be a good intermediate step to a bigger change?

**Comment by kevinkjt2000** [comment]
I second testing an empty prefix.  Some of the friends I recommend ellipsis to would prefer having no prefix.

**Comment by groggemans** [comment]
As the prefixing stuff only matters at installation time I wouldn't mind to alter the default to an empty prefix and just break backward compatibility. (won't affect installed packages)

Just not a big fan of the extra repo selection magic, but that's a personal opinion. :slightly_smiling_face: 

So if I get it right we all wan't to default to an empty prefix, and the question is if we should break backward compatibility for `dot-*` packages or not?

**Comment by groggemans** [comment]
@zeekay what's your opinion on those ideas?

**Comment by zeekay** [comment]
I chose `dot-` so I could easily filter/identify my packages, locally and on GitHub. Assuming everyone else adopts the convention, it could make discovery on GitHub easier. Then again, if no one knows about / understands the convention it's a net negative.

I don't mind switching to empty prefix, but it would be nice to gather community consensus somehow.

**Comment by groggemans** [comment]
@zeekay @kevinkjt2000 Is it ok if I merge this in? It's not changing the current behavior, but will provide some flexibility until we sort this out. If ok, I'll make an issue about defaulting to en empty prefix, so people searching about this can leave their preferences or ideas there.

**Comment by zeekay** [comment]
Yeah that sounds good!

**Pull request merged**
